//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectDebitSMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthLoan
    {
        public int AuthLoansId { get; set; }
        public string ACCO_BROKER_NUMBER { get; set; }
        public string ORGA_NAME { get; set; }
        public string ACCO_BROKER_REF { get; set; }
        public Nullable<int> ACCO_ORGAN_NUMBER { get; set; }
        public Nullable<int> ACCO_SUFFIX { get; set; }
        public Nullable<int> ACCO_PARENT_LOAN_SUFFIX { get; set; }
        public string ACCO_NAME { get; set; }
        public Nullable<System.DateTime> ACCO_APPLICATION_REC_DATE { get; set; }
        public Nullable<System.DateTime> ACCO_DATE_PENDING { get; set; }
        public Nullable<System.DateTime> ACCO_BROKER_PAY_DATE { get; set; }
        public Nullable<System.DateTime> ACCO_DATE_CANCELLED { get; set; }
        public Nullable<System.DateTime> ACCO_RENEWAL_DATE { get; set; }
        public Nullable<decimal> ACCO_PREMIUM_AMOUNT { get; set; }
        public Nullable<double> ACCO_INTEREST_RATE_USED { get; set; }
        public Nullable<double> CENTRALISED_OVERRIDER__ { get; set; }
        public Nullable<double> CENTRALISED_OVERRIDER__1 { get; set; }
        public Nullable<double> ACCO_COMMISSION_RATE { get; set; }
        public Nullable<double> ACCO_OVERRIDER { get; set; }
        public string ACCO_STATUS { get; set; }
        public string CONTACT { get; set; }
        public string ACCO_BROKER_CONTACT_NAME { get; set; }
        public Nullable<System.DateTime> SCHE_DATE { get; set; }
        public Nullable<decimal> SCHE_AMOUNT { get; set; }
        public string FIRST_INSTALMENT_TYPE { get; set; }
        public Nullable<bool> SELECTED_FOR_TEXT { get; set; }
    }
}
